### ISSUE TITLE
Need white/light one

### ISSUE THREAD

**Issue by lovebdsobuj** [Nidre/VS2015-Dark-Npp#15]

**Comment by Ludomancer** [comment]
@lovebdsobuj 

I don't have any plans to do that any time soon since I don't use the light theme. Maybe if I have some extra free time I can create another repository for it.

But in any case, this repository is only intended for Dark Theme. Closing this bug.

Feel free to fork and create the Light Theme based on this if you would like.

**Comment by lovebdsobuj** [comment]
Is there any tools/gui that can I use for edit this theme with Live preview?
Or need to manually edit color codes?
